### ISSUE TITLE
Can't run specs

### ISSUE THREAD

**Issue by AlexWayfer** [opal/opal-jquery#93] opened 2016-11-13 12:37 UTC
`$ bundle install` — OK
`$ bundle exec rackup` — OK
Visiting `http://localhost:9292` — doesn't OK
<details>
  <summary>Output in console</summary>
  <p>

```
::1 - - [13/Nov/2016:15:29:40 +0300] "GET / HTTP/1.1" 500 - 0.0218
NoMethodError: undefined method `get_opal_spec_requires' for #<Sprockets::CachedEnvironment:0x007f42e4518d48>
	/home/alex/.gem/ruby/2.3.0/bundler/gems/opal-rspec-d2cdb3aa98fa/opal/opal/rspec/sprockets_runner.rb.erb:8:in `_evaluate_template'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/erb_processor.rb:26:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/erb_processor.rb:13:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:23:in `block in call'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/utils.rb:196:in `dfs'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:24:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/environment.rb:30:in `find_asset'
	/home/alex/.gem/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:92:in `[]'
	/home/alex/.gem/ruby/2.3.0/gems/opal-0.10.3/lib/opal/sprockets.rb:74:in `javascript_include_tag'
	/home/alex/.gem/ruby/2.3.0/gems/opal-0.10.3/lib/opal/sprockets/server.rb:114:in `javascript_include_tag'
	spec/jquery/index.html.erb:8:in `block in singleton class'
	spec/jquery/index.html.erb:-6:in `instance_eval'
	spec/jquery/index.html.erb:-6:in `singleton class'
	spec/jquery/index.html.erb:-8:in `__tilt_69962635337140'
	/home/alex/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
	/home/alex/.gem/ruby/2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
	/home/alex/.gem/ruby/2.3.0/gems/opal-0.10.3/lib/opal/sprockets/server.rb:102:in `html'
	/home/alex/.gem/ruby/2.3.0/gems/opal-0.10.3/lib/opal/sprockets/server.rb:92:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/deflater.rb:35:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/opal-0.10.3/lib/opal/sprockets/server.rb:79:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/show_exceptions.rb:23:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/common_logger.rb:33:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/chunked.rb:54:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/content_length.rb:15:in `call'
	/home/alex/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```
  </p>
</details>

**Comment by AlexWayfer** [comment] 2016-11-13 14:22
`$ bundle exec rake` — OK
<details>
  <summary>Output in console</summary>
  <p>

```
Running phantomjs /home/alex/.gem/ruby/2.3.0/bundler/gems/opal-rspec-d2cdb3aa98fa/vendor/spec_runner.js "http://localhost:9999/"
Object freezing is not supported by Opal

..................................................................................................................................................

Finished in 4.65 seconds (files took 0.28 seconds to load)
146 examples, 0 failures
```
  </p>
</details>

`$ bundle exec rake zepto` — doesn't OK
<details>
  <summary>Output in console</summary>
  <p>

```
Running phantomjs /home/alex/.gem/ruby/2.3.0/bundler/gems/opal-rspec-d2cdb3aa98fa/vendor/spec_runner.js "http://localhost:9999/"
Object freezing is not supported by Opal

undefined native method `stop' for class `Element'

  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1588 in alias_native
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:2402 in $$alias_native
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:58197
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:58727
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:58734
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:59299
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:59363
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:59390
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:61945
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
Specs timed out

  phantomjs://code/spec_runner.js:49
```
  </p>
</details>

**Comment by zw963** [comment] 2017-08-18 15:25
I occur this now. 

Following is a very simple example project, 

https://github.com/zw963/opal_rspec_example#zypto_branch

When run with:  `bundle exec rake zypto`, got
```sh
rake aborted!
Don't know how to build task 'zypto'
/home/zw963/.rvm/gems/ruby-2.3.4@opal_rspec_example/bin/ruby_executable_hooks:15:in `eval'
/home/zw963/.rvm/gems/ruby-2.3.4@opal_rspec_example/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

when run with: `bundle exec rake`, got
```sh
undefined native method `stop' for class `Element'

  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1588 in alias_native
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:2403 in $$alias_native
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:58289
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:58819
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:58826
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:59391
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:59403
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:59412
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1981 in require
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:60420
  http://localhost:9999/assets/opal/rspec/sprockets_runner.js:1957 in load
Specs timed out
```

**Comment by zw963** [comment] 2017-08-18 15:27
@AlexWayfer ,  could you please give me a link about how to add
![img](http://i.imgur.com/5rnC5CC.png) in github issue ?

**Comment by AlexWayfer** [comment] 2017-08-18 20:31
> @AlexWayfer , could you please give me a link about how to add
img in github issue ? (that arrow)

https://github.com/dear-github/dear-github/issues/166#issuecomment-252282315

**Comment by elia** [comment] 2018-11-09 17:35
The specs are still kinda broken, it's known, we had some talk with @catmando about using capybara and hyper-spec but I think the work is still in progress.

Meanwhile I'll close this one, thanks for the report.

**Closed by elia** 2018-11-09 17:35 UTC

**Comment by elia** [comment] 2018-11-10 01:04
> Is there any PR?

There's no PR so far.

> Why? It isn't resolved yet.

And it's not resolved, but it's also well reflected on the [project's front page](https://github.com/opal/opal-jquery#opal-jquery) where the travis badge says `build error` 😓. This is the reason there's no need to keep an issue open. I closed the issue not because the problem is resolved, but because we're already _resolved_ to fix the problem 😅.

If you want to open a PR to fix the spec suite that would be awesome, meanwhile I'll check with @catmando to see if the work is actually still going on or if it has stalled. Thanks again for the report!
